@startuml

abstract class Reunion {
    - fecha: Date
    - horaPrevista: Instant
    - duracionPrevista: Duration
    - horaInicio: Instant
    - horaFin: Instant;
    - invitaciones : Map<Invitable, Invitacion>


    + obtenerAsistencia() : List
    + obtenerAusencias() : List
    + ontenerRetrasos() : List
    + obtenerTotalAsistencia() : int
    + obtenerPorcentajeAsistencia() : float
    + calcularTiempoReal() : float
    + iniciar() : void
    + finalizar() : void
    + agregarInvitacion(Invitable invitado, Invitacion invitacion) : void
}

enum TipoReunion {
  * Tecnica
  * Maketing
  * Otro
}

enum EstadoAsistencia {
    * Presente
    * Ausente
    * Tarde
}

class Nota {
  - contenido : String

  +getContenido() : String
  +setContenido(String contenido) : Void
  +toString() : String
}

class Invitacion {
  - hora : Instant

  +getHora() : Instant
  +setHora(Instant hora) : void
}

class Asistencia {
    - empleado : Empleado
    - estado : EstadoAsistencia

    + getEmpleado() : empleado
    + getEstado() : EstadoAsistencia
}

interface Invitable {

    +invitar(Reunion reunion, Instant horaInvitacion) : void
}

class ReunionVirtual {
    - enlace : String
}

class ReunionPresencial {
    - sala : String
}

class Retraso {
    - horaLllegadaTarde : Instant

    +getHoraLlegadaTarde() : Instant
}

class Empleado {
    - id : Int
    - apellidos : String
    - nombre : String
    - correo : String
    - departamento : Departamento

    +getId() : Int
    +getNombre() : String
    +getApellido() : String
    +getCorreo() : String
    +getDepartamento() : Departamento
    +invitar(Reunion reunion, Instant horaInvitacion) : void


}

class Departamento {
    - nombre : String
    - empleados : List<Empleado>

    +addEmpleado(Empleado empleado) : void
    +getNombre() : String
    +getEmpleado() : List<Empleado>
    +obtenerCantidadEmpleados() : int
    +invitar(Reunion reunion, Instant horaInvitacion) : void
}

Nota --* Reunion
Asistencia --* Reunion
Invitacion --* Reunion
ReunionVirtual --|> Reunion
ReunionPresencial --|> Reunion
Reunion --> TipoReunion
Invitacion --> Invitable
Retraso --|> Asistencia
Reunion  --> Empleado: organizado por
Empleado --o Departamento
Empleado ..|> Invitable
Departamento ..|> Invitable
Asistencia --> EstadoAsistencia
Retraso --> EstadoAsistencia

@enduml
